import pandas as pd
import os
from os.path import join

def extract_markers(filepath: str):
    # Read raw CSV generated by GENEActiv Software  
    df = pd.read_csv(filepath, skiprows = 100, 
                     names = ['time stamp', 'mean x', 'mean y', 'mean z', 'mean lux', 'button', 
                            'temperature', 'sum of vector', 'x sd', 'y sd', 'z sd', 'lux peak'])
    
    # Filter out rows where button == 0
    df = df[df['button'] != 0]
    
    # keep only time stamp and button
    df = df[['time stamp', 'button']]
    
    return(df)

def bulk_extract_markers(in_dir: str, out_dir: str, create_dir: bool = True): 
    if not os.path.exists(in_dir):
        raise FileNotFoundError(f"Input directory '{in_dir}' does not exist.")
    
    if not os.path.exists(out_dir):
        # Create output directory if it does not exist
        if create_dir:
            os.makedirs(out_dir)
            print(f"Directory '{out_dir}' created.")
        else :
            raise FileNotFoundError(f"Output directory '{out_dir}' does not exist.")
        
    for entry in os.scandir(in_dir):
        # Check if entry is a valid csv file
        if entry.is_file() and entry.name.endswith('.csv'):
            markers = extract_markers(join(in_dir, entry.name))
            out_path = join(out_dir, f"{os.path.splitext(entry.name)[0]}_markers.csv")
            markers.to_csv(out_path, index = False)
